[book]
authors = ["Sagi"]
title = "The LearnixOS Book"
language = "en"
src = "src"

[preprocessor.mdbook-rust-analyzer-highlight]
whichlang = true
command = "cargo run --release --manifest-path mdbook-rust-analyzer-highlight/Cargo.toml"
project-root = "./LearnixOS"
inlay-hint-config = "inlay_config.json"

[preprocessor.gh-issue-preview]
after = ["mdbook-rust-analyzer-highlight"]
command = "cargo run --release --manifest-path mdbook-gh-issue-preview/Cargo.toml"

[preprocessor.webinclude]
before = ["mdbook-rust-analyzer-highlight"]

[output.html]
git-repository-url = "https://github.com/sagi21805/LearnixOS"
default-theme = "navy"
preferred-dark-theme = "navy"
preferred-light-theme = "navy"
additional-css = ["theme/whichlang.css", "theme/hlrs.css", "theme/gh-issue.css", "theme/tags.css"]
additional-js = [
    "theme/whichlang.js",
    "theme/filepath-links.js",
    "theme/giscuss.js",
    "theme/tags.js"
]
mathjax-support = true
