[book]
authors = ["Sagi"]
title = "The LearnixOS Book"
language = "en"
src = "src"

[preprocessor.rust-highlight]
whichlang = true
command = "cargo run --release --manifest-path mdbook-rust-highlight/Cargo.toml"

[preprocessor.rust-highlight.mapping]
present = "Function"
code_or_data = "Function"
executable = "Function"
direction = "Function"
conforming = "Function"
readable = "Function"
writable = "Function"
granularity = "Function"
protected = "Function"
long = "Function"
LimitFlags = "Type"
usr_access = "Function"
write_through_cache = "Function"
disable_cache = "Function"
huge_page = "Function"
global = "Function"
full = "Function"
table = "Function"
root_entry = "Function"
not_executable = "Function"
Backspace = "Enum"
LineFeed = "Enum"
Delete = "Enum"

[preprocessor.gh-issue-preview]
after = ["rust-highlight"]
command = "cargo run --release --manifest-path mdbook-gh-issue-preview/Cargo.toml"

[preprocessor.webinclude]
before = ["rust-highlight"]

[output.html]
git-repository-url = "https://github.com/sagi21805/LearnixOS"
default-theme = "navy"
preferred-dark-theme = "navy"
preferred-light-theme = "navy"
additional-css = ["theme/whichlang.css", "theme/hlrs.css", "theme/gh-issue.css"]
additional-js = [
    "theme/whichlang.js",
    "theme/filepath-links.js",
    "theme/giscuss.js",
]
mathjax-support = true
