name: deploy

on:
  workflow_run:
    workflows: [validate]
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install mdBook and mdbook-linkcheck (cached by action)
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook@0.5.3,mdbook-linkcheck,mdbook-utils,mdbook-webinclude

      - name: Create sitemap
        run: mdbook-utils sitemap -m src -b https://www.learnix-os.com -o src/assets/sitemap.xml

      - name: Build the book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "book"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
