name: validate

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check the Spelling of the Book
        uses: crate-ci/typos@v1.47.0
