name: validate

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:


jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-linkcheck,mdbook-webinclude

      - name: Show versions & locations
        run: |
          mdbook --version
          mdbook-linkcheck --version || true
          mdbook-webinclude --version || true
          which mdbook || whereis mdbook
          which mdbook-webinclude || whereis mdbook-webinclude

      - name: Run mdbook (verbose + backtrace)
        env:
          RUST_BACKTRACE: 1
        run: mdbook build -v

  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action Repository
        uses: actions/checkout@v4

      - name: Check the Spelling of the Book
        uses: crate-ci/typos@v1.34.0

